



wget -O /tmp/gatk-4.0.11.0.zip https://github.com/broadinstitute/gatk/releases/download/4.0.11.0/gatk-4.0.11.0.zip && \
unzip /tmp/gatk-4.0.11.0.zip -d /usr/local/pipeline/Tools && \
chmod -R 777 /usr/local/pipeline/Tools && \
export PATH=$PATH:/usr/local/pipeline/Tools/gatk-4.0.11.0
cp -rfv /usr/local/pipeline/Tools/gatk-4.0.11.0/* /usr/local/bin
